### PR TITLE
Introduced support for signRawTransactionWithKey

### PR DESCRIPTION
**Pull request by cd2357**

### CODE REVIEW

**Comment by Polve** [comment]
The integration tests seems not to run with "mvn test", how may I run them?

**Comment by cd2357** [comment]
With #100, "mvn test" works for me. Can you check if it also works for you?

**Comment by Polve** [comment]
It works, but in IntegrationTestBase I need to manually specify:
>     	client = new BitcoinJSONRPCClient(DEFAULT_JSONRPC_REGTEST_URL);
Otherwise it will try to connect to a non-existent production node.

Thanks!

**Comment by cd2357** [comment]
No problem.

I realized I'm also manually hardcoding the API endpoint in the code, because it was not clear to me how the library configures the API endpoint it connects to.

So I looked into it and added some documentation with #101.

Now I'm using bitcoin.conf to configure both bitcoind and this library -- no more manual changes in the code.

Using that, do you still need to do that manual change in IntegrationTestBase?

**Pull request merged**
