### PR TITLE
Extend getBlockChainInfo call

### PR DESCRIPTION
**Pull request by cd2357**
The call now returns almost all properties returned by the API.

### CODE REVIEW

**Comment by Polve** [comment]
Nice parsing for the default config file, too bad that nowadays on the most common linux distro (ubuntu) bitcoin core is packaged as a snap and the config file is in ~/snap/bitcoin-core/common/.bitcoin/bitcoin.conf
Maybe you can add the code to look for it too?

**Comment by cd2357** [comment]
Thanks.

About the path in Ubuntu -- wasn't aware of that, I'll have a look.

**Comment by cd2357** [comment]
On Linux, I usually just download and extract the bitcoind zip, then directly call the executable. No matter where I place it, it creates the .bitcoin config folder (with bitcoin.conf and all else) directly in the home folder.

I guess it works differently when installed via snap.

**Comment by Polve** [comment]
Yes, also snaps can be installed on almost all platforms with just one build so I guess they can become very popular and that's one of the reasons why they changed the packaging: until a few releases ago they were usual .deb packages and hence used the usual ~/.bitcoin/bitcoin.conf configuration file

**Comment by cd2357** [comment]
Correct me if I'm wrong, but from what I understand, the path to a snap's user data contains the snap version?

As per https://snapcraft.io/docs/environment-variables an example of the HOME variable is

> /home/zyga/snap/hello-world/27

where 27 is the snap version.

Is that correct?

If so, the path to the snap bitcoin.conf would practically change with every snap update.

**Comment by Polve** [comment]
It's correct, but there is also a common folder for data that does not change between versions.

That's why in case of bitcoin-core the config file is  ~/snap/bitcoin-core/common/.bitcoin/bitcoin.conf

Anyway, there is also a symbolic link to the current version, so you can have a fixed path also for apps using that folder for data. That would be something like  ~/snap/bitcoin-core/current/XXXX.

**Comment by cd2357** [comment]
Done with #104, please check if it works for you.

**Pull request merged**
